name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pylint

      - name: Rodar Pylint
        run: |
          pylint main.py || true
      


